name: "AFL++ fuzzing action"
description: "Action to run fuzz tests using AFL++"
inputs:
  campaign_name:
    description: "Name of your campaign"
    default: "none"
  fuzz_target:
    description: "Target binary to be fuzzed"
    required: true
  input_folder:
    description: "Path of the input folder used as seed corpus"
    required: true
  output_folder:
    description: "Path of the output folder where crashes and state are saved"
    required: true
  timeout:
    description: "Time to wait if the fuzzer hangs"
    default: 10
  time:
    description: "Fuzzing time"
    default: 120
  qemu_mode:
    description: "QEMU Mode"
    default: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.campaign_name }}
    - ${{ inputs.fuzz_target }}
    - ${{ inputs.input_folder }}
    - ${{ inputs.output_folder }}
    - ${{ inputs.timeout }}
    - ${{ inputs.time }}
    - ${{ inputs.qemu_mode }}